from .categoria_licencia_views import *
from .subcategoria_licencia_views import *
from .cliente_views import *
from .vehiculo_views import *
from .reserva_views import *
from .devolucion_views import *
from .factura_views import *
from .auth_views import *
from .home_views import *
from .panel_views import *
