# Generated by Django 5.2.8 on 2025-11-28 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='core.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15),
        ),
    ]
